Fixed watch page
tiemfah/tedxKasetU2019 pull request #7
Opened 2019-10-27 06:23 UTC by llleyelll

Please review:
- [ ] All videos work well
- [ ] Responsive

2019-10-27 06:45 UTC, tiemfah commented
it works!

2019-10-27 06:47 UTC, tiemfah commented on next.config.js
> +        "/watch": { page: "/watch" },
add your page here

2019-10-27 06:48 UTC, tiemfah requested changes
add your page to next.config.js so next.js will render it.

2019-10-27 07:31 UTC, llleyelll commented on next.config.js
> +        "/watch": { page: "/watch" },
Got it ka 👍

2019-10-27 09:12 UTC, tiemfah approved these changes

2019-10-27 12:21 UTC, patdpat approved these changes

2019-10-28 09:06 UTC, llleyelll commented
Please review the watch page:
- [] All videos work well
- [] Responsive

Please review sponsor page:
- [] Accordion work
- [] Responsive

2019-10-28 14:44 UTC, Klan300 approved these changes

2019-10-31 04:56 UTC, Sirikonss approved these changes

2019-10-31 08:00 UTC, merged